# Generated by Django 6.0.3 on 2026-03-10 10:39

import django.core.validators
import django.db.models.deletion
import kyc_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(help_text='e.g. IN, US', max_length=5)),
                ('dial_code', models.CharField(help_text='e.g. +91, +1', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], max_length=20)),
                ('document_name', models.CharField(help_text='e.g. GST Number, PAN, VAT', max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc_app.countrymaster')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc_app.officemaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], db_index=True, max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('KYC_PENDING', 'KYC Pending'), ('PENDING_APPROVAL', 'KYC Approval Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'KYC Expiry'), ('INACTIVE', 'Inactive')], db_index=True, default='DRAFT', max_length=30)),
                ('person1_name', models.CharField(max_length=255)),
                ('person1_phone', models.CharField(max_length=20)),
                ('person2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person2_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('full_address', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_swift', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kyc_app.countrymaster')),
                ('master_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='kyc_app.masteruser')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kyc_app.officemaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_value', models.CharField(blank=True, help_text='ID/Number from the doc', max_length=255, null=True)),
                ('file_upload', models.FileField(upload_to=kyc_app.models.user_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kyc_app.documentrequirement')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc_app.userdetail')),
            ],
        ),
        migrations.AddIndex(
            model_name='documentrequirement',
            index=models.Index(fields=['user_type', 'country', 'office'], name='kyc_app_doc_user_ty_3bdc32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentrequirement',
            unique_together={('user_type', 'country', 'office', 'document_name')},
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['user_detail', 'is_active'], name='kyc_app_use_user_de_5928cb_idx'),
        ),
    ]
