# Generated by Django 6.0.3 on 2026-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrymaster',
            name='country_code',
        ),
        migrations.AddField(
            model_name='countrymaster',
            name='code_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='2-Letter Code'),
        ),
        migrations.AddField(
            model_name='countrymaster',
            name='code_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='3-Letter Code'),
        ),
        migrations.AlterField(
            model_name='countrymaster',
            name='dial_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dial Code'),
        ),
        migrations.AlterField(
            model_name='countrymaster',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
