# Generated by Django 6.0.3 on 2026-03-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0002_alter_userdetail_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('PORTAL', 'Via Portal')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_docs', to='kyc_app.masteruser'),
        ),
    ]
