# Generated by Django 6.0.3 on 2026-03-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0002_remove_countrymaster_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officemaster',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='kyc_app.countrymaster'),
        ),
    ]
