# Generated by Django 6.0.3 on 2026-03-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0003_officemaster_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
            },
        ),
        migrations.RenameIndex(
            model_name='documentrequirement',
            new_name='kyc_app_doc_user_ty_9d0e8f_idx',
            old_name='kyc_app_doc_user_ty_3bdc32_idx',
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='kyc_app.usertypemaster'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='kyc_app.usertypemaster'),
        ),
    ]
