# Generated by Django 6.0.3 on 2026-03-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0003_userdocument_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='validity_date',
            field=models.DateField(blank=True, help_text='Until when the document is valid', null=True),
        ),
    ]
