# Generated by Django 6.0.3 on 2026-03-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0004_userdocument_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='remarks',
            field=models.TextField(blank=True, help_text='Review remarks', null=True),
        ),
    ]
